applications:
  next:
    type: nodejs:22
    build:
      flavor: none
    web:
      locations:
        "/":
          passthru: true
      commands:
        start: "node /app/out/standalone/server.js"
      upstream:
        socket_family: tcp
    hooks:
      build: |
        set -x -e
        npm install
        npm run build

routes:
  "https://{all}/": { type: upstream, upstream: "next:http", id: "next" }
  "http://{all}/": { type: redirect, to: "https://{all}/" }